//
//  VulkanOptionSets.h
//  Volcano
//
//  Created by Serhii Mumriak on 17.08.2020.
//

#ifndef VulkanOptionSets_h
#define VulkanOptionSets_h 1

#include "../CCore/include/CCore.h"

AK_EXISTING_OPTIONS(VkAccelerationStructureCreateFlagBitsKHR);
AK_EXISTING_OPTIONS(VkAccessFlagBits);
AK_EXISTING_OPTIONS(VkAttachmentDescriptionFlagBits);
AK_EXISTING_OPTIONS(VkBufferCreateFlagBits);
AK_EXISTING_OPTIONS(VkBufferUsageFlagBits);
AK_EXISTING_OPTIONS(VkBuildAccelerationStructureFlagBitsKHR);
AK_EXISTING_OPTIONS(VkColorComponentFlagBits);
AK_EXISTING_OPTIONS(VkCommandBufferResetFlagBits);
AK_EXISTING_OPTIONS(VkCommandBufferUsageFlagBits);
AK_EXISTING_OPTIONS(VkCommandPoolCreateFlagBits);
AK_EXISTING_OPTIONS(VkCommandPoolResetFlagBits);
AK_EXISTING_OPTIONS(VkCompositeAlphaFlagBitsKHR);
AK_EXISTING_OPTIONS(VkConditionalRenderingFlagBitsEXT);
AK_EXISTING_OPTIONS(VkCullModeFlagBits);
AK_EXISTING_OPTIONS(VkDebugReportFlagBitsEXT);
AK_EXISTING_OPTIONS(VkDebugUtilsMessageSeverityFlagBitsEXT);
AK_EXISTING_OPTIONS(VkDebugUtilsMessageTypeFlagBitsEXT);
AK_EXISTING_OPTIONS(VkDependencyFlagBits);
AK_EXISTING_OPTIONS(VkDescriptorBindingFlagBits);
AK_EXISTING_OPTIONS(VkDescriptorPoolCreateFlagBits);
AK_EXISTING_OPTIONS(VkDescriptorSetLayoutCreateFlagBits);
AK_EXISTING_OPTIONS(VkDeviceDiagnosticsConfigFlagBitsNV);
AK_EXISTING_OPTIONS(VkDeviceGroupPresentModeFlagBitsKHR);
AK_EXISTING_OPTIONS(VkDeviceQueueCreateFlagBits);
AK_EXISTING_OPTIONS(VkDisplayPlaneAlphaFlagBitsKHR);
AK_EXISTING_OPTIONS(VkEventCreateFlagBits);
AK_EXISTING_OPTIONS(VkExternalFenceFeatureFlagBits);
AK_EXISTING_OPTIONS(VkExternalFenceHandleTypeFlagBits);
AK_EXISTING_OPTIONS(VkExternalMemoryFeatureFlagBits);
AK_EXISTING_OPTIONS(VkExternalMemoryFeatureFlagBitsNV);
AK_EXISTING_OPTIONS(VkExternalMemoryHandleTypeFlagBits);
AK_EXISTING_OPTIONS(VkExternalMemoryHandleTypeFlagBitsNV);
AK_EXISTING_OPTIONS(VkExternalSemaphoreFeatureFlagBits);
AK_EXISTING_OPTIONS(VkExternalSemaphoreHandleTypeFlagBits);
AK_EXISTING_OPTIONS(VkFenceCreateFlagBits);
AK_EXISTING_OPTIONS(VkFenceImportFlagBits);
AK_EXISTING_OPTIONS(VkFormatFeatureFlagBits);
AK_EXISTING_OPTIONS(VkFramebufferCreateFlagBits);
AK_EXISTING_OPTIONS(VkGeometryFlagBitsKHR);
AK_EXISTING_OPTIONS(VkGeometryInstanceFlagBitsKHR);
AK_EXISTING_OPTIONS(VkImageAspectFlagBits);
AK_EXISTING_OPTIONS(VkImageCreateFlagBits);
AK_EXISTING_OPTIONS(VkImageUsageFlagBits);
AK_EXISTING_OPTIONS(VkImageViewCreateFlagBits);
AK_EXISTING_OPTIONS(VkIndirectCommandsLayoutUsageFlagBitsNV);
AK_EXISTING_OPTIONS(VkIndirectStateFlagBitsNV);
AK_EXISTING_OPTIONS(VkMemoryAllocateFlagBits);
AK_EXISTING_OPTIONS(VkMemoryHeapFlagBits);
AK_EXISTING_OPTIONS(VkMemoryPropertyFlagBits);
AK_EXISTING_OPTIONS(VkPeerMemoryFeatureFlagBits);
AK_EXISTING_OPTIONS(VkPerformanceCounterDescriptionFlagBitsKHR);
AK_EXISTING_OPTIONS(VkPipelineCacheCreateFlagBits);
AK_EXISTING_OPTIONS(VkPipelineCreateFlagBits);
AK_EXISTING_OPTIONS(VkPipelineCreationFeedbackFlagBitsEXT);
AK_EXISTING_OPTIONS(VkPipelineShaderStageCreateFlagBits);
AK_EXISTING_OPTIONS(VkPipelineStageFlagBits);
AK_EXISTING_OPTIONS(VkQueryControlFlagBits);
AK_EXISTING_OPTIONS(VkQueryPipelineStatisticFlagBits);
AK_EXISTING_OPTIONS(VkQueryResultFlagBits);
AK_EXISTING_OPTIONS(VkQueueFlagBits);
AK_EXISTING_OPTIONS(VkRenderPassCreateFlagBits);
AK_EXISTING_OPTIONS(VkRenderingFlagBitsKHR);
AK_EXISTING_OPTIONS(VkResolveModeFlagBits);
AK_EXISTING_OPTIONS(VkSampleCountFlagBits);
AK_EXISTING_OPTIONS(VkSamplerCreateFlagBits);
AK_EXISTING_OPTIONS(VkSemaphoreImportFlagBits);
AK_EXISTING_OPTIONS(VkSemaphoreWaitFlagBits);
AK_EXISTING_OPTIONS(VkShaderStageFlagBits);
AK_EXISTING_OPTIONS(VkSparseImageFormatFlagBits);
AK_EXISTING_OPTIONS(VkSparseMemoryBindFlagBits);
AK_EXISTING_OPTIONS(VkStencilFaceFlagBits);
AK_EXISTING_OPTIONS(VkSubgroupFeatureFlagBits);
AK_EXISTING_OPTIONS(VkSubmitFlagBitsKHR);
AK_EXISTING_OPTIONS(VkSubpassDescriptionFlagBits);
AK_EXISTING_OPTIONS(VkSurfaceCounterFlagBitsEXT);
AK_EXISTING_OPTIONS(VkSurfaceTransformFlagBitsKHR);
AK_EXISTING_OPTIONS(VkSwapchainCreateFlagBitsKHR);
#ifdef VK_USE_PLATFORM_ANDROID_KHR
AK_EXISTING_OPTIONS(VkSwapchainImageUsageFlagBitsANDROID);
#endif
AK_EXISTING_OPTIONS(VkToolPurposeFlagBitsEXT);

#endif /* VulkanOptionSets_h */
